/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'pavel' at '10/16/16 8:16 PM' with Gradle 2.13
 *
 * @author pavel, @date 10/16/16 8:16 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
