/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'pavel' at '10/16/16 8:16 PM' with Gradle 2.13
 *
 * @author pavel, @date 10/16/16 8:16 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
